// ============================================================
// BACKYARD SURVIVOR WIKI — SEASON DATA
// ============================================================
// This is the ONLY file you need to edit to update the wiki.
// Replace placeholder data with your real season info.
// ============================================================

export const SEASONS = [
  {
    id: 1,
    name: "Season 1",
    subtitle: "The Beginning",
    location: "The Backyard",
    filmingDates: "Summer 2024",
    episodes: 10,
    days: 14,
    winner: "Player 1",
    runnerUp: "Player 2",
    fanFavorite: "Player 3",
    tribes: [
      { name: "Tribe A", color: "#e74c3c" },
      { name: "Tribe B", color: "#3498db" },
    ],
    cast: [
      {
        name: "Player 1",
        tribe: "Tribe A",
        age: 18,
        hometown: "Your City",
        bio: "The winner of Season 1.",
        placement: 1,
        juryMember: false,
        votesAgainst: 2,
        challengeWins: 3,
        daysLasted: 14,
      },
      {
        name: "Player 2",
        tribe: "Tribe B",
        age: 17,
        hometown: "Your City",
        bio: "Runner-up of Season 1.",
        placement: 2,
        juryMember: false,
        votesAgainst: 4,
        challengeWins: 2,
        daysLasted: 14,
      },
      {
        name: "Player 3",
        tribe: "Tribe A",
        age: 18,
        hometown: "Your City",
        bio: "Fan favorite of Season 1.",
        placement: 3,
        juryMember: true,
        votesAgainst: 3,
        challengeWins: 1,
        daysLasted: 12,
      },
      {
        name: "Player 4",
        tribe: "Tribe B",
        age: 17,
        hometown: "Your City",
        bio: "A strong competitor.",
        placement: 4,
        juryMember: true,
        votesAgainst: 5,
        challengeWins: 2,
        daysLasted: 11,
      },
      {
        name: "Player 5",
        tribe: "Tribe A",
        age: 16,
        hometown: "Your City",
        bio: "Known for big moves.",
        placement: 5,
        juryMember: true,
        votesAgainst: 3,
        challengeWins: 1,
        daysLasted: 10,
      },
      {
        name: "Player 6",
        tribe: "Tribe B",
        age: 18,
        hometown: "Your City",
        bio: "A social threat.",
        placement: 6,
        juryMember: true,
        votesAgainst: 4,
        challengeWins: 0,
        daysLasted: 9,
      },
      {
        name: "Player 7",
        tribe: "Tribe A",
        age: 17,
        hometown: "Your City",
        bio: "The underdog story.",
        placement: 7,
        juryMember: true,
        votesAgainst: 6,
        challengeWins: 1,
        daysLasted: 8,
      },
      {
        name: "Player 8",
        tribe: "Tribe B",
        age: 16,
        hometown: "Your City",
        bio: "A strategic player.",
        placement: 8,
        juryMember: true,
        votesAgainst: 4,
        challengeWins: 0,
        daysLasted: 7,
      },
      {
        name: "Player 9",
        tribe: "Tribe A",
        age: 18,
        hometown: "Your City",
        bio: "Early merge boot.",
        placement: 9,
        juryMember: true,
        votesAgainst: 5,
        challengeWins: 1,
        daysLasted: 6,
      },
      {
        name: "Player 10",
        tribe: "Tribe B",
        age: 17,
        hometown: "Your City",
        bio: "Pre-merge player.",
        placement: 10,
        juryMember: false,
        votesAgainst: 7,
        challengeWins: 0,
        daysLasted: 5,
      },
      {
        name: "Player 11",
        tribe: "Tribe A",
        age: 16,
        hometown: "Your City",
        bio: "Pre-merge player.",
        placement: 11,
        juryMember: false,
        votesAgainst: 5,
        challengeWins: 0,
        daysLasted: 4,
      },
      {
        name: "Player 12",
        tribe: "Tribe B",
        age: 18,
        hometown: "Your City",
        bio: "Early elimination.",
        placement: 12,
        juryMember: false,
        votesAgainst: 8,
        challengeWins: 0,
        daysLasted: 3,
      },
      {
        name: "Player 13",
        tribe: "Tribe A",
        age: 17,
        hometown: "Your City",
        bio: "Second boot.",
        placement: 13,
        juryMember: false,
        votesAgainst: 6,
        challengeWins: 0,
        daysLasted: 2,
      },
      {
        name: "Player 14",
        tribe: "Tribe B",
        age: 16,
        hometown: "Your City",
        bio: "First boot of the season.",
        placement: 14,
        juryMember: false,
        votesAgainst: 9,
        challengeWins: 0,
        daysLasted: 1,
      },
    ],
    votingHistory: [
      {
        episode: 1,
        tribal: "Tribe B",
        votes: { "Player 14": "Player 1", "Player 12": "Player 14", "Player 10": "Player 14", "Player 8": "Player 14", "Player 6": "Player 14", "Player 4": "Player 14", "Player 2": "Player 14" },
        eliminated: "Player 14",
        notes: "",
      },
      {
        episode: 2,
        tribal: "Tribe A",
        votes: { "Player 13": "Player 5", "Player 11": "Player 13", "Player 9": "Player 13", "Player 7": "Player 13", "Player 5": "Player 13", "Player 3": "Player 13", "Player 1": "Player 13" },
        eliminated: "Player 13",
        notes: "",
      },
      {
        episode: 3,
        tribal: "Tribe B",
        votes: { "Player 12": "Player 10", "Player 10": "Player 12", "Player 8": "Player 12", "Player 6": "Player 12", "Player 4": "Player 12", "Player 2": "Player 12" },
        eliminated: "Player 12",
        notes: "",
      },
      {
        episode: 4,
        tribal: "Tribe A",
        votes: { "Player 11": "Player 9", "Player 9": "Player 11", "Player 7": "Player 11", "Player 5": "Player 11", "Player 3": "Player 11", "Player 1": "Player 11" },
        eliminated: "Player 11",
        notes: "",
      },
      {
        episode: 5,
        tribal: "Tribe B",
        votes: { "Player 10": "Player 8", "Player 8": "Player 10", "Player 6": "Player 10", "Player 4": "Player 10", "Player 2": "Player 10" },
        eliminated: "Player 10",
        notes: "Last pre-merge tribal.",
      },
      {
        episode: 6,
        tribal: "Merged",
        votes: { "Player 9": "Player 4", "Player 8": "Player 9", "Player 7": "Player 9", "Player 6": "Player 9", "Player 5": "Player 9", "Player 4": "Player 9", "Player 3": "Player 4", "Player 2": "Player 9", "Player 1": "Player 9" },
        eliminated: "Player 9",
        notes: "Merge episode.",
      },
      {
        episode: 7,
        tribal: "Merged",
        votes: { "Player 8": "Player 1", "Player 7": "Player 8", "Player 6": "Player 8", "Player 5": "Player 8", "Player 4": "Player 8", "Player 3": "Player 8", "Player 2": "Player 8", "Player 1": "Player 8" },
        eliminated: "Player 8",
        notes: "",
      },
      {
        episode: 8,
        tribal: "Merged",
        votes: { "Player 7": "Player 1", "Player 6": "Player 7", "Player 5": "Player 7", "Player 4": "Player 7", "Player 3": "Player 7", "Player 2": "Player 7", "Player 1": "Player 7" },
        eliminated: "Player 7",
        notes: "",
      },
      {
        episode: 9,
        tribal: "Merged",
        votes: { "Player 6": "Player 1", "Player 5": "Player 6", "Player 4": "Player 6", "Player 3": "Player 6", "Player 2": "Player 6", "Player 1": "Player 6" },
        eliminated: "Player 6",
        notes: "",
      },
      {
        episode: 10,
        tribal: "Merged",
        votes: { "Player 5": "Player 2", "Player 4": "Player 5", "Player 3": "Player 5", "Player 2": "Player 5", "Player 1": "Player 5" },
        eliminated: "Player 5",
        notes: "",
      },
    ],
    challenges: [
      { episode: 1, type: "Reward", name: "Opening Relay", description: "Obstacle course relay race.", winner: "Tribe A" },
      { episode: 1, type: "Immunity", name: "Puzzle Rush", description: "Slide puzzle race.", winner: "Tribe A" },
      { episode: 2, type: "Immunity", name: "Blindfolded Maze", description: "Navigate a maze blindfolded with verbal guidance.", winner: "Tribe B" },
      { episode: 3, type: "Immunity", name: "Water Carry", description: "Carry water through an obstacle course.", winner: "Tribe A" },
      { episode: 4, type: "Immunity", name: "Endurance Hold", description: "Hold a weighted bar as long as possible.", winner: "Tribe B" },
      { episode: 5, type: "Immunity", name: "Slingshot Targets", description: "Hit targets with a slingshot.", winner: "Tribe A" },
      { episode: 6, type: "Immunity", name: "Balance Beam Showdown", description: "Individual balance beam endurance.", winner: "Player 1" },
      { episode: 7, type: "Reward", name: "Trivia Throwdown", description: "Survivor trivia questions.", winner: "Player 3" },
      { episode: 7, type: "Immunity", name: "Rope Climb", description: "Climb rope obstacles.", winner: "Player 5" },
      { episode: 8, type: "Immunity", name: "Card Stacking", description: "Build the tallest card tower.", winner: "Player 1" },
      { episode: 9, type: "Immunity", name: "Dizzy Bat Race", description: "Spin around a bat and race to the finish.", winner: "Player 1" },
      { episode: 10, type: "Immunity", name: "Final Endurance", description: "Last one standing wins.", winner: "Player 1" },
    ],
  },
  {
    id: 2,
    name: "Season 2",
    subtitle: "Unfinished Business",
    location: "The Backyard",
    filmingDates: "Summer 2025",
    episodes: 10,
    days: 14,
    winner: "Returnee 1",
    runnerUp: "Newbie 1",
    fanFavorite: "Returnee 3",
    tribes: [
      { name: "Vets", color: "#e67e22" },
      { name: "Rookies", color: "#2ecc71" },
    ],
    cast: [
      {
        name: "Returnee 1",
        tribe: "Vets",
        age: 19,
        hometown: "Your City",
        bio: "Came back to finish the job.",
        placement: 1,
        juryMember: false,
        votesAgainst: 1,
        challengeWins: 4,
        daysLasted: 14,
      },
      {
        name: "Newbie 1",
        tribe: "Rookies",
        age: 17,
        hometown: "Your City",
        bio: "The best newcomer of the season.",
        placement: 2,
        juryMember: false,
        votesAgainst: 3,
        challengeWins: 2,
        daysLasted: 14,
      },
      {
        name: "Returnee 3",
        tribe: "Vets",
        age: 18,
        hometown: "Your City",
        bio: "Fan favorite who played hard.",
        placement: 3,
        juryMember: true,
        votesAgainst: 4,
        challengeWins: 2,
        daysLasted: 12,
      },
      {
        name: "Newbie 2",
        tribe: "Rookies",
        age: 16,
        hometown: "Your City",
        bio: "Scrappy underdog.",
        placement: 4,
        juryMember: true,
        votesAgainst: 5,
        challengeWins: 1,
        daysLasted: 11,
      },
      {
        name: "Returnee 2",
        tribe: "Vets",
        age: 18,
        hometown: "Your City",
        bio: "Strategic mastermind.",
        placement: 5,
        juryMember: true,
        votesAgainst: 3,
        challengeWins: 1,
        daysLasted: 10,
      },
      {
        name: "Newbie 3",
        tribe: "Rookies",
        age: 17,
        hometown: "Your City",
        bio: "Physical beast.",
        placement: 6,
        juryMember: true,
        votesAgainst: 6,
        challengeWins: 2,
        daysLasted: 9,
      },
      {
        name: "Returnee 4",
        tribe: "Vets",
        age: 17,
        hometown: "Your City",
        bio: "The social butterfly.",
        placement: 7,
        juryMember: true,
        votesAgainst: 5,
        challengeWins: 0,
        daysLasted: 8,
      },
      {
        name: "Newbie 4",
        tribe: "Rookies",
        age: 18,
        hometown: "Your City",
        bio: "Quiet but dangerous.",
        placement: 8,
        juryMember: true,
        votesAgainst: 4,
        challengeWins: 1,
        daysLasted: 7,
      },
      {
        name: "Returnee 5",
        tribe: "Vets",
        age: 16,
        hometown: "Your City",
        bio: "Came back with a chip on their shoulder.",
        placement: 9,
        juryMember: true,
        votesAgainst: 7,
        challengeWins: 0,
        daysLasted: 6,
      },
      {
        name: "Newbie 5",
        tribe: "Rookies",
        age: 17,
        hometown: "Your City",
        bio: "Pre-merge casualty.",
        placement: 10,
        juryMember: false,
        votesAgainst: 6,
        challengeWins: 0,
        daysLasted: 5,
      },
      {
        name: "Returnee 6",
        tribe: "Vets",
        age: 18,
        hometown: "Your City",
        bio: "Quick exit the second time around.",
        placement: 11,
        juryMember: false,
        votesAgainst: 8,
        challengeWins: 0,
        daysLasted: 4,
      },
      {
        name: "Newbie 6",
        tribe: "Rookies",
        age: 16,
        hometown: "Your City",
        bio: "Targeted early.",
        placement: 12,
        juryMember: false,
        votesAgainst: 7,
        challengeWins: 0,
        daysLasted: 3,
      },
      {
        name: "Returnee 7",
        tribe: "Vets",
        age: 17,
        hometown: "Your City",
        bio: "Couldn't escape the target.",
        placement: 13,
        juryMember: false,
        votesAgainst: 9,
        challengeWins: 0,
        daysLasted: 2,
      },
      {
        name: "Newbie 7",
        tribe: "Rookies",
        age: 18,
        hometown: "Your City",
        bio: "First one out.",
        placement: 14,
        juryMember: false,
        votesAgainst: 10,
        challengeWins: 0,
        daysLasted: 1,
      },
    ],
    votingHistory: [
      {
        episode: 1,
        tribal: "Rookies",
        votes: { "Newbie 7": "Newbie 3", "Newbie 6": "Newbie 7", "Newbie 5": "Newbie 7", "Newbie 4": "Newbie 7", "Newbie 3": "Newbie 7", "Newbie 2": "Newbie 7", "Newbie 1": "Newbie 7" },
        eliminated: "Newbie 7",
        notes: "",
      },
      {
        episode: 2,
        tribal: "Vets",
        votes: { "Returnee 7": "Returnee 2", "Returnee 6": "Returnee 7", "Returnee 5": "Returnee 7", "Returnee 4": "Returnee 7", "Returnee 3": "Returnee 7", "Returnee 2": "Returnee 7", "Returnee 1": "Returnee 7" },
        eliminated: "Returnee 7",
        notes: "",
      },
    ],
    challenges: [
      { episode: 1, type: "Reward", name: "Opening Sprint", description: "Sprint relay with puzzle finish.", winner: "Vets" },
      { episode: 1, type: "Immunity", name: "Tower Build", description: "Build the tallest block tower.", winner: "Vets" },
      { episode: 2, type: "Immunity", name: "Tug of War", description: "Classic tug of war.", winner: "Rookies" },
    ],
  },
  {
    id: 3,
    name: "Season 3",
    subtitle: "The Outpost",
    location: "TBD",
    filmingDates: "Coming Soon",
    episodes: null,
    days: null,
    winner: null,
    runnerUp: null,
    fanFavorite: null,
    tribes: [],
    cast: [],
    votingHistory: [],
    challenges: [],
  },
];
